FROM python:3.11-slim-bookworm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the rest of the application
COPY . .

RUN python3 -m venv .venv && . .venv/bin/activate \
    && pip install --upgrade pip && pip install --no-cache-dir -r ./requirements.txt \
    && black whisperflow tests && pylint --fail-under=9.9 whisperflow tests \
    && pytest --ignore=tests/benchmark --ignore=tests/audio --cov-fail-under=95 --cov whisperflow -v tests
